#!/bin/sh
xrandr \
  --output DP-0 --mode 2560x1440 --pos 0x0 --rotate normal \
  --output DVI-D-0 --off \
  --output DP-1 --off \
  --output HDMI-0 --mode 2560x1440 --pos 2560x0 --rotate normal

xrandr \
  --output DP-0 --mode 2560x1440 --pos 2560x0 --rotate normal \
  --output DVI-D-0 --off --output DP-1 --off \
  --output HDMI-0 --mode 2560x1440 --pos 0x0 --rotate normal

